config/routes.rb
Rails.application.routes.draw do

  resources :trips do
    get 'search', on: :collection
  end

  root 'trips#index'

end

app/models/trip.rb
class Trip < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:name, :image, :discription, :video, :duration, :length, :cost, :temp, :places_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", http: {equiv: "Content-Type"}}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no"}
    %title Exploro | The breathtaking road trips for you
    = favicon_link_tag       'map.ico'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    / Fixed navbar
    %nav.navbar.navbar.navbar-fixed-top
      .container
        .navbar-header
          %a.navbar-brand{href: "/"}
            %span.fa-stack
              %i.fa.fa-map-o.fa-stack-1x
              %i.fa.fa-map-marker.fa-stack-1x
            %span
              EXPLORO
            %span.separater
              &#9474;
          %form.navbar-form.navbar-left.navbar-brand.search-form{role: 'search'}
            .form-group
              %i.fa.fa-search
              %input.form-control

    = yield

    %footer.footer
      .container
        %span
          %h4 CATEGORIES

app/views/trips/_form.html.haml
= form_for @trip do |f|
  - if @trip.errors.any?
    #error_explanation
      %h2= "#{pluralize(@trip.errors.count, "error")} prohibited this trip from being saved:"
      %ul
        - @trip.errors.full_messages.each do |msg|
          %li= msg

  .field.form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .field.form-group
    = f.label :image
    = f.text_field :image, class: 'form-control'
  .field.form-group
    = f.label :discription
    = f.text_field :discription, class: 'form-control'
  .field.form-group
    = f.label :video
    = f.text_field :video, class: 'form-control'
  .field.form-group
    = f.label :duration
    = f.number_field :duration, class: 'form-control'
  .field.form-group
    = f.label :length
    = f.number_field :length, class: 'form-control'
  .field.form-group
    = f.label :cost
    = f.number_field :cost, class: 'form-control'
  .field.form-group
    = f.label :temp
    = f.number_field :temp, class: 'form-control'
  .field.form-group
    = f.label :places_count
    = f.number_field :places_count, class: 'form-control'
  %button.btn.btn-default{type: 'submit'} SUBMIT

app/views/trips/edit.html.haml
%h1 Editing trip

= render 'form'

= link_to 'Show', @trip
\|
= link_to 'Back', trips_path

app/views/trips/index.html.haml
/ Begin page content
.jumbotron.page-header
  .cover-overlay
  .container.statement
    %h1 Explore The World.
    %p.lead
      -# Lorem Ipsum er ganske enkelt fyldtekst fra print- og typografiindustrien.

.main-contents
  .container
    .row
      - @trips.each do |trip|
        .col-sm-6.col-md-4.trip-view
          = link_to trip_path(trip) do
            .thumbnail{style: "background-image: url(#{trip.image})"}
              .thumb-overlay
              .caption
                %h3= trip.name

app/views/trips/new.html.haml
%h1 New trip

= render 'form'

= link_to 'Back', trips_path

app/views/trips/show.html.haml
.detail-contents
  .container
    .row
      .col-xs-12.detail-view
        .thumbnail
          %h3{style: "margin-top: 12px"}
            = @trip.name
    .row
      .col-xs-4.col-md-2.detail-view
        .thumbnail
          %h3= @trip.duration
          %h5 days
      .col-xs-4.col-md-2.detail-view
        .thumbnail
          %h3= @trip.length
          %h5 km
      .col-xs-4.col-md-2.detail-view
        .thumbnail
          %h3= @trip.cost
          %h5 $
      .col-xs-4.col-md-2.detail-view
        .thumbnail
          %h3= @trip.temp
          %h5 °F
      .col-xs-4.col-md-2.detail-view
        .thumbnail
          %h3= @trip.places_count
          %h5 Stops
      .col-xs-4.col-md-2.detail-view
        .thumbnail
          %h4= @trip.start
          %h6 to
          %h4= @trip.goal

.jumbotron.page-footer{style: "background-image: url(#{@trip.image})"}
  .cover-overlay
  .container.statement
    %h4= @trip.discription